version: "3"
services:
  leafy-postgres:
    image: m020202/leafy-postgres:294e1473fe1b270ea561bc041203bc2b3075ebaa
    volumes:
      - mydata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
    restart: always

  leafy-backend:
    build: ./leafy-backend
    image: leafy-backend:5.0.0-compose
    environment:
      - DB_URL=leafy-postgres
    depends_on:
      - leafy-postgres
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 512M
    restart: on-failure

  leafy-front:
    image: m020202/leafy-frontend:e9d8fcb91c4b98159cbe677db49726c071615fe2
    environment:
      - BACKEND_HOST=leafy-backend
    ports:
      - 80:80
    depends_on:
      - leafy-backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
    restart: on-failure

volumes:
  mydata:
